# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @importFrom Rcpp sourceCpp
#' @useDynLib DCM
NULL

frequencyDistributionCpp <- function(cold) {
    .Call('_DCM_frequencyDistributionCpp', PACKAGE = 'DCM', cold)
}

createConceptsCpp <- function(data_matrix, nmax_choiceset_size = 31L) {
    .Call('_DCM_createConceptsCpp', PACKAGE = 'DCM', data_matrix, nmax_choiceset_size)
}

#' llCalc3
#' does the calc
#' actually llCalc3a does, this is same but other cant export
#' @returns loglike
#' @export
llCalc3 <- function(working_values, model, processed, draws_matrix) {
    .Call('_DCM_llCalc3', PACKAGE = 'DCM', working_values, model, processed, draws_matrix)
}

#' llMax2
#' does the maximisation
#'
#' @returns opt_results
#' @export
llMax2 <- function(model, processed, draws_matrix) {
    .Call('_DCM_llMax2', PACKAGE = 'DCM', model, processed, draws_matrix)
}

