# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @importFrom Rcpp sourceCpp
#' @useDynLib DCM
NULL

#' @export
frequencyDistributionCpp <- function(cold) {
    .Call('_DCM_frequencyDistributionCpp', PACKAGE = 'DCM', cold)
}

