# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
    paths:
      - '**.R'
      - '**.cpp'
  pull_request:
    branches: [main, master]
    paths:
      - '**.R'
      - '**.cpp'

name: R-CMD-check and Lint

jobs:
  lint:
      runs-on: ubuntu-latest
      env:
        GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      steps:
        - uses: actions/checkout@v3

        - uses: r-lib/actions/setup-r@v2
          with:
            use-public-rspm: true

        - uses: r-lib/actions/setup-r-dependencies@v2
          with:
            extra-packages: any::lintr, local::.
            needs: lint

        - name: Lint
          run: lintr::lint_package()
          shell: Rscript {0}
          env:
            LINTR_ERROR_ON_LINT: true

  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest,   r: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          args: 'c("--no-vignettes", "--no-build-vignettes", "--ignore-vignettes")'
          build_args: 'c("--no-build-vignettes")'
          upload-snapshots: true

